### ISSUE TITLE
Cmake Solution

### ISSUE THREAD

**Issue by martell** [GerHobbelt/pthread-win32#1]
Hi Ger,

I plan on creating a cmake solution for pthread-win32.
It would be a better way to handle different Visual studio version changes.

Your though's on this and on maybe helping me?

Cheers
Martell

**Comment by GerHobbelt** [comment]
Resolved this year (*long* overdue) by merging work from forks in commit 9129f2e190ae488883a91219cff9eefedb5a17fb

Work was done in commits 98a45e53d9c8ced60c8fb72be2be38098bce9e60
 and 113d3298398eb8648a939e912510d5750294848a, among others.
