### ISSUE TITLE
VS 2008 project does not compile

### ISSUE THREAD

**Issue by fredmcfly2** [GerHobbelt/pthread-win32#12]
Attempting to compile by using the Microsoft Visual Studio 2008. The project does not compile.
133 errors.

Most are the error:
`fatal error C1189: #error :  "config.h was not #included"`

The remaining errors are related to missing files, such as:
`fatal error C1083: Cannot open source file: '.\fork.c': No such file or directory`
`fatal error C1083: Cannot open source file: '.\spin.c': No such file or directory`

**Comment by fredmcfly2** [comment]
If I define `HAVE_CONFIG_H` then I get the following preprocessor error:
` error RC2188: C:\Workspace\RecMngr\external\pthreads\obj\pthread_lib_Win32_MSVC2008.Debug\RCa13980(406) : fatal error RC1116: RC terminating after preprocessor errors`

**Comment by zhenguoli** [comment]
You can solve this problem by add a definition "PTW32_ARCHx86" in "Properities > Resources > General > Preprocessor Definitions" according to the `version.c`:
```
#if defined(PTW32_RC_MSC)
#  if defined(PTW32_ARCHx64)
#    define PTW32_ARCH "x64"
#  elif defined(PTW32_ARCHx86)
#    define PTW32_ARCH "x86"
#  else
#    error "PTW32_ARCHx64 / PTW32_ARCHx86 has not been defined"
#  endif
...
```

**Comment by GerHobbelt** [comment]
(After a hiatus of a decade.)

Closing this one as a solution was provided above (thanks!) and I consider MSVC2008 outdated today.

Please file a new issue & cross-ref to this one if this is a problem for legacy projects.
