### ISSUE TITLE
missing test tsd3 using i686-w64-mingw32-gcc

### ISSUE THREAD

**Issue by pmalhaire** [GerHobbelt/pthread-win32#6]
Hi,
I noticed that when I runned the tests suite the tsd3 test is missing,
it is normal that there is no such tsd3.c or did I just miss something and its generated else where ?

I use GC-static-debug for both lib and tests

thanks for your help
Pierre

**Comment by GerHobbelt** [comment]
Nope, apparently something got screwed up back then (forgot to add tsd3.c to the repo, or so it seems) and now the development machines which stored copies of the pthread codebase are all dead, so all we can do now is forget it ever existed. :'-(

**Comment by GerHobbelt** [comment]
This one is fixed in #7.
